import { useState, useRef, useEffect } from 'react'
import {
  Send,
  Sparkles,
  BookOpen,
  FileText,
  Bookmark,
  CheckCircle2,
  HelpCircle,
  Copy,
  Info
} from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const DEMO_LECTURES = [
  {
    id: 'lec_all',
    title: 'All Uploaded Material',
    module: 'Global Vector Search',
    chunks: 175,
  },
  {
    id: 'lec_1',
    title: 'Lec01_Introduction_to_AI.pdf',
    module: 'CS 401: AI',
    chunks: 48,
  },
  {
    id: 'lec_2',
    title: 'Lec04_Heuristic_Search_A_Star.pdf',
    module: 'CS 401: AI',
    chunks: 64,
  },
  {
    id: 'lec_3',
    title: 'Lec03_Deep_Neural_Networks.docx',
    module: 'CS 480: ML',
    chunks: 39,
  },
  {
    id: 'lec_4',
    title: 'Lec02_Bayesian_Inference.pdf',
    module: 'STAT 350: Prob',
    chunks: 25,
  },
]

const INITIAL_MESSAGES = [
  {
    id: 'msg_1',
    sender: 'ai',
    text: "Hello! I'm your AI StudyMate assistant. I only answer using the verified lecture notes and PDFs you've uploaded, and every answer includes precise page citations.",
    citation: null,
    time: '10:00 AM',
  },
  {
    id: 'msg_2',
    sender: 'user',
    text: 'What is the difference between an admissible heuristic and a consistent heuristic in A* search?',
    citation: null,
    time: '10:02 AM',
  },
  {
    id: 'msg_3',
    sender: 'ai',
    text: "Based on your lecture notes on heuristic search:\n\n1. **Admissible Heuristic:** An admissible heuristic $h(n)$ never overestimates the true cost to reach the goal (it is optimistic). Formally, $0 \\le h(n) \\le h^*(n)$ for all nodes $n$.\n\n2. **Consistent (Monotonic) Heuristic:** A heuristic is consistent if for every node $n$ and every successor $n'$ generated by an action $a$ with step cost $c(n, a, n')$, the triangle inequality holds:\n$$h(n) \\le c(n, a, n') + h(n')$$\n\n**Key Takeaway:** Consistency is a strictly stronger condition than admissibility. Every consistent heuristic is admissible, but not all admissible heuristics are consistent. Consistency guarantees optimal graph search without needing to reopen closed nodes.",
    citation: 'Lec04_Heuristic_Search_A_Star.pdf — Page 14 & 16',
    time: '10:02 AM',
  },
]

export default function ChatPage() {
  const { user } = useAuth()
  const [selectedLecture, setSelectedLecture] = useState(DEMO_LECTURES[2])
  const [messages, setMessages] = useState(INITIAL_MESSAGES)
  const [inputText, setInputText] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages, isTyping])

  const handleSendMessage = (textToSend) => {
    const query = textToSend || inputText
    if (!query.trim()) return

    const userMessage = {
      id: 'msg_' + Date.now(),
      sender: 'user',
      text: query.trim(),
      citation: null,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    }

    setMessages((prev) => [...prev, userMessage])
    if (!textToSend) setInputText('')
    setIsTyping(true)

    // Simulate RAG vector retrieval & response generation
    setTimeout(() => {
      let aiResponseText = ''
      let citationText = ''

      if (query.toLowerCase().includes('early stopping') || query.toLowerCase().includes('overfitting')) {
        aiResponseText =
          'Early stopping acts as a regularization technique by monitoring validation performance during gradient descent. Training is halted automatically once validation loss fails to decrease for a preset number of consecutive epochs (patience). This prevents the weights from fitting high-frequency noise in the training set.'
        citationText = 'Lec03_Deep_Neural_Networks.docx — Page 18'
      } else if (query.toLowerCase().includes('bayes') || query.toLowerCase().includes('prior')) {
        aiResponseText =
          'Bayes Theorem computes posterior probability by updating the prior belief with observed evidence likelihood:\n\n$$P(A|B) = \\frac{P(B|A) P(A)}{P(B)}$$\n\nWhere $P(A)$ is the prior, $P(B|A)$ is the likelihood, and $P(B)$ is the marginal evidence probability.'
        citationText = 'Lec02_Bayesian_Inference.pdf — Page 7'
      } else {
        aiResponseText = `According to your uploaded materials in **${selectedLecture.title}**, the relevant sections highlight:\n\n- The core theoretical concept is defined through empirical evaluation.\n- Key formulas and assumptions apply under standard boundary constraints.\n- Check section 3.2 for the step-by-step derivation.`
        citationText = `${selectedLecture.title} — Page ${Math.floor(Math.random() * 20) + 1}`
      }

      const aiMessage = {
        id: 'msg_' + (Date.now() + 1),
        sender: 'ai',
        text: aiResponseText,
        citation: citationText,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      }

      setMessages((prev) => [...prev, aiMessage])
      setIsTyping(false)
    }, 1000)
  }

  const promptSuggestions = [
    'Explain early stopping to prevent overfitting',
    'Summarize Bayes Theorem formula and terms',
    'What is an admissible heuristic in A*?',
  ]

  return (
    <div className="stagger-children">
      {/* Page Header */}
      <div className="page-header" style={{ marginBottom: 'var(--space-4)' }}>
        <div className="page-header-actions">
          <div>
            <h1>RAG-Powered AI Study Chat</h1>
            <p>Every response is retrieved from your notes and backed by a cited lecture + page number.</p>
          </div>
          <div className="badge badge-accent">
            <Sparkles size={14} /> Citations Guaranteed
          </div>
        </div>
      </div>

      {/* Two-Panel Chat Container */}
      <div className="chat-layout">
        {/* Left Panel: Lecture Selector & Context */}
        <div className="chat-sidebar">
          <div className="chat-sidebar-header">
            <div style={{ fontSize: 'var(--text-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 'var(--space-2)' }}>
              Active Knowledge Context
            </div>
            <div style={{ fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>
              Select which lecture to ground responses against:
            </div>
          </div>

          <div className="chat-sidebar-list">
            {DEMO_LECTURES.map((lec) => (
              <div
                key={lec.id}
                className={`chat-sidebar-item ${selectedLecture.id === lec.id ? 'active' : ''}`}
                onClick={() => setSelectedLecture(lec)}
              >
                <div className="chat-sidebar-item-icon">
                  <FileText size={18} />
                </div>
                <div className="chat-sidebar-item-info">
                  <div className="chat-sidebar-item-title">{lec.title}</div>
                  <div className="chat-sidebar-item-module">{lec.module} • {lec.chunks} chunks</div>
                </div>
              </div>
            ))}
          </div>

          <div style={{ padding: 'var(--space-3)', borderTop: '1px solid var(--border)', background: 'var(--bg)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>
              <Info size={14} style={{ flexShrink: 0, color: 'var(--primary)' }} />
              <span>Answers reference page numbers from active PDFs.</span>
            </div>
          </div>
        </div>

        {/* Right Panel: Chat Thread */}
        <div className="chat-main">
          {/* Messages Thread */}
          <div className="chat-messages">
            {messages.map((msg) => (
              <div key={msg.id} className={`chat-message ${msg.sender}`}>
                <div className="chat-message-avatar">
                  {msg.sender === 'ai' ? (
                    <div className="avatar avatar-sm avatar-accent" style={{ background: 'var(--accent)', color: 'white' }}>
                      AI
                    </div>
                  ) : (
                    <div className="avatar avatar-sm avatar-primary">
                      {user ? user.avatar : 'ME'}
                    </div>
                  )}
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', maxWidth: '100%' }}>
                  <div className="chat-message-content" style={{ whiteSpace: 'pre-wrap' }}>
                    {msg.text}
                  </div>

                  {msg.citation && (
                    <div className="chat-citation">
                      <BookOpen size={13} style={{ color: 'var(--accent)' }} />
                      <span>Source: <strong>{msg.citation}</strong></span>
                    </div>
                  )}

                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '4px', alignSelf: msg.sender === 'user' ? 'flex-end' : 'flex-start' }}>
                    {msg.time}
                  </span>
                </div>
              </div>
            ))}

            {isTyping && (
              <div className="chat-message ai">
                <div className="avatar avatar-sm avatar-accent" style={{ background: 'var(--accent)', color: 'white' }}>
                  AI
                </div>
                <div className="chat-message-content animate-pulse" style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', fontSize: 'var(--text-sm)', color: 'var(--text-secondary)' }}>
                  <Sparkles size={16} className="animate-spin" style={{ color: 'var(--accent)' }} />
                  Searching pgvector chunks & drafting cited answer...
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Quick Prompt Suggestions */}
          <div style={{ padding: '0 var(--space-5) var(--space-2)', display: 'flex', gap: 'var(--space-2)', overflowX: 'auto' }}>
            {promptSuggestions.map((prompt, idx) => (
              <button
                key={idx}
                type="button"
                className="btn btn-secondary btn-sm"
                style={{ fontSize: 'var(--text-xs)', padding: '4px 10px', borderRadius: 'var(--radius-full)' }}
                onClick={() => handleSendMessage(prompt)}
              >
                💬 {prompt}
              </button>
            ))}
          </div>

          {/* Input Bar */}
          <div className="chat-input-bar">
            <div className="chat-input-wrapper">
              <textarea
                className="chat-input"
                rows={1}
                placeholder={`Ask any question about ${selectedLecture.title}...`}
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault()
                    handleSendMessage()
                  }
                }}
              />
            </div>
            <button
              type="button"
              className="chat-send-btn"
              onClick={() => handleSendMessage()}
              disabled={!inputText.trim() || isTyping}
              aria-label="Send message"
            >
              <Send size={18} />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
